Blog/Models/Comments/MainComment.cs
namespace Blog.Models.Comments
{
    public class MainComment : Comment
    {
        public List<SubComment> SubComments { get; set; }
    }
}

Blog/Areas/Admin/Controllers/PostController.cs
using Blog.Interfaces;
using Blog.Models;
using Blog.Utility;
using Blog.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize(Roles =SD.Role_Admin)]
    public class PostController : Controller
    {
        private readonly IRepository _repo;
        private readonly IFileManager _fileManager;

        public PostController(IRepository repo, 
            IFileManager fileManager)
        {
            _repo = repo;
            _fileManager = fileManager;
        }
        public IActionResult Index()
        {
            var posts = _repo.GetAllPosts();
            return View(posts);
        }

        public IActionResult Details(int id)
        {
            return View(_repo.GetPost(id));
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return View(new PostViewModel());
            else
            {
                var post = _repo.GetPost((int)id);
                return View(new PostViewModel
                {
                    Id = post.Id,
                    Title = post.Title,
                    Body = post.Body,
                    CurrentImage = post.Image,
                    Description = post.Description,
                    Category = post.Category,
                    Tags = post.Tags
                });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(PostViewModel vm)
        {
            var post = new Post
            {
                Id = vm.Id,
                Title = vm.Title,
                Body = vm.Body,
                Description = vm.Description,
                Category = vm.Category,
                Tags = vm.Tags

            };
            if (vm.Image == null)
            {
                post.Image = vm.CurrentImage;
            }
            else
            {
                post.Image = await _fileManager.SaveImage(vm.Image);

            }

            if (post.Id > 0)
                _repo.UpdatePost(post);
            else
                _repo.AddPost(post);

            if (await _repo.SaveChangeAsync())
                return RedirectToAction("Index");
            else
                return View(vm);
        }
        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            _repo.RemovePost(id);
            await _repo.SaveChangeAsync();
            return RedirectToAction("Index");
        }

        [HttpGet("/Image/{image}")]
        [ResponseCache(CacheProfileName = "Monthly")]
        public IActionResult Image(string image)
        {
            var mine = image.Substring(image.LastIndexOf('.') + 1);
            return new FileStreamResult(_fileManager.ImageStream(image), $"image/{mine}");
        }
    }
}

Blog/Views/Shared/_AdminNavbar.cshtml
<!-- Sidebar -->
<div class="bg-light border-right" id="sidebar-wrapper">
    <div class="sidebar-heading"><a class="list-group-item-action" href="/Panel/FrontPage"><i class="fa fa-pie-chart fa-2x"></i>Admin Dashboard</a></div>
    <div class="clearfix"></div>
    <div class="list-group list-group-flush">
        <a data-toggle="collapse" href="#collapseExample" aria-expanded="true" class="list-group-item list-group-item-action bg-light"><i class=" fa fa-plus-circle fa-2x"></i>Pages</a>
        <div class="clearfix"></div>
        <div class="collapse in" id="collapseExample">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" routerLinkActive="active">
                    <a class="list-group-item list-group-item-action bg-light link-collapse" asp-controller="Home" asp-action="HomeEdit">
                        <i class="fa fa-home fa-2x"></i>Home-Page
                    </a>
                </li>
                <li class="nav-item" routerLinkActive="active">
                    <a class="list-group-item list-group-item-action bg-light link-collapse" asp-controller="Home" asp-action="Edit">Edit Home-Page</a>
                </li>
                <li class="nav-item" routerLinkActive="active">
                    <a class="list-group-item list-group-item-action bg-light link-collapse" asp-controller="Home" asp-action="Index">About-Page</a>
                </li>
                <li class="nav-item" routerLinkActive="active">
                    <a class="list-group-item list-group-item-action bg-light link-collapse" asp-area="Admin" asp-controller="MyMessages" asp-action="Index">
                        <i class="fa fa-envelope-o fa-2x"></i>My Messages
                    </a>
                </li>
                <li class="nav-item" routerLinkActive="active">
                    <a class="list-group-item list-group-item-action bg-light link-collapse" asp-area="Admin" asp-controller="MyPost" asp-action="Index">
                        <i class="fa fa-pencil-square-o fa-2x"></i>My Posts
                    </a>
                </li>
                <li class="nav-item" routerLinkActive="active">
                    <a class="list-group-item list-group-item-action bg-light link-collapse" asp-area="Admin" asp-controller="MyPortfolio" asp-action="Index">
                        <i class="fa fa-sticky-note fa-2x"></i> Portfolio-list
                    </a>
                </li>
                <li class="nav-item" routerLinkActive="active">
                    <a class="list-group-item list-group-item-action bg-light link-collapse" asp-controller="Members" asp-action="Index">
                        <i class="fa fa-users fa-2x"></i> Member-List
                    </a>
                </li>
            </ul>
        </div>
        <div class="clearfix"></div>
        <a href="#" class="list-group-item list-group-item-action bg-light"><i class="fa fa-bookmark-o fa-2x"></i>Overview</a>
        <a asp-controller="Calendar" asp-action="Index" class="list-group-item list-group-item-action bg-light">
            <i class="fa fa-calendar fa-2x"></i>Events
        </a>
        <a href="#" class="list-group-item list-group-item-action bg-light"><i class="fa fa-play fa-2x"></i>Status</a>
    </div>
</div>

Blog/Views/Shared/_Layout.cshtml
@using Blog.Utility

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Islam Blog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!-- Google fonts-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"></script>
    <link href="//fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <link href="~/css/styles.css" rel="stylesheet" />
    <link href="~/css/custom.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <!-- Summernote CSS Reference -->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
</head>
<body>
    <!-- preloader start -->
    <div class="preloader">
        <div class="spin"></div>
    </div>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img style="height:40px;width:150px" src="~/images/bg/IMG_٢٠٢٥٠٢٠٢_١٥١٦١٩.jpg" /> Blog </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-area="UI" asp-controller="Post" asp-action="Index">Posts</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-area="UI" asp-controller="Home" asp-action="About">About</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-area="UI" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    @if (User.IsInRole(SD.Role_Admin))
                    {
                        <li class="nav-item">
                            <a class="nav-link px-lg-3 py-3 py-lg-4" asp-area="Admin" asp-controller="Post" asp-action="Edit">Create Post</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link px-lg-3 py-3 py-lg-4" asp-area="Admin" asp-controller="Post" asp-action="Index">List Post</a>
                        </li>
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
        <!-- Page Header-->
       <header class="masthead">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>@ViewData["MainText"]</h1>
                            <span class="subheading">@ViewData["SubText"]</span>
                          <form asp-action="SearchIndex" asp-controller="Posts">
                                <div class="input-group input-group-sm mt-5">
                                    <input type="text" name="SearchTerm" class="form-control rounded-start" placeholder="Search Term" />
                                    <div class="input-group-append d-grid">
                                        <button class="btn btn-warning rounded-end" style="right:5px;" type="submit">Search</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    <div class="container">
            @RenderBody()
    </div>
    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="https://www.youtube.com/channel/UCymPTmdV5goU-IBMCAPaErQ" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-youtube fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.linkedin.com/in/martin-fernandez-b465b47a/" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-linkedin-in fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://github.com/UxDeveloper82" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; <img style="height:25px;width:90px" src="~/images/bg/IMG_٢٠٢٥٠٢٠٢_١٥١٦١٩.jpg" />   Blog  2025</div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/scrollNav.js"></script>
    <script src="~/js/postlist.js"></script>
   
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
    <script>
        (function ($) {
            'use strict';
            // Preloader js
            $(window).on('load', function () {
                $('.preloader').fadeOut(700);
            });
        })(jQuery);
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Blog/Views/Shared/_MainComment.cshtml
@model CommentViewModel

@{

}

<style>
    .post__comments {
        display: flex;
        flex-direction: column;
        margin-top: 10px;
    }

    .post__input {
        flex: 1;
        border: none;
        padding: 10px;
        border-top: 1px solid lightgray;
    }
</style>

<div>
    <form method="post" asp-controller="Post" asp-action="Comment" class="post__comments">
        <input asp-for="PostId" type="hidden" />
        <input asp-for="MainCommentId" type="hidden" />
        <textarea class="form-control" asp-for="Message" placeholder="Add a comment..."></textarea>
        <button class="post__button btn btn-outline-primary" type="submit">Submit</button>
    </form>
</div>